// AUTO-GENERATED by scripts/build-api-manifest.mjs — DO NOT EDIT.
// 재생성: `npm run dev` / `npm run build` (predev/prebuild 훅) 또는 `npm run manifest`.
// 결정적 출력 — 같은 입력이면 byte-identical.

import type { GeneratedManifest } from "./types";

export const MANIFEST: GeneratedManifest = {
  "endpoints": [
    {
      "path": "/api/admin/crawl/regions",
      "id": "admin-crawl-regions",
      "filePath": "app/api/admin/crawl/regions/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/admin/crawl",
      "id": "admin-crawl",
      "filePath": "app/api/admin/crawl/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        },
        {
          "method": "POST",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        },
        {
          "method": "PATCH",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        },
        {
          "method": "DELETE",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/admin/users",
      "id": "admin-users",
      "filePath": "app/api/admin/users/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        },
        {
          "method": "POST",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        },
        {
          "method": "PATCH",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        },
        {
          "method": "PUT",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        },
        {
          "method": "DELETE",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/buildings/by-pnu",
      "id": "buildings-by-pnu",
      "filePath": "app/api/buildings/by-pnu/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/capa/by-bjd",
      "id": "capa-by-bjd",
      "filePath": "app/api/capa/by-bjd/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/capa/by-jibun",
      "id": "capa-by-jibun",
      "filePath": "app/api/capa/by-jibun/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": {
            "source": "DB (Supabase: kepco_capa + bjd_master)",
            "cache": "no-store",
            "auth": "user",
            "inputs": [
              {
                "name": "bjd_code",
                "type": "string",
                "required": true,
                "sample": "4673025025",
                "description": "법정동 코드 10자리"
              },
              {
                "name": "jibun",
                "type": "string",
                "required": true,
                "sample": "20-1",
                "description": "지번 (예: 20, 20-1, 산5-3)"
              }
            ],
            "outputSchema": "{ ok, bjd_code, jibun, rows: KepcoDataRow[], total, meta: AddrMeta | null }",
            "externalDeps": [],
            "notes": "exact match 만 — fallback 없음. KEPCO 미수집 지번은 빈 rows 반환. meta 는 bjd_master 의 sep_1~5 (헤더 주소 표시용 보조 데이터)."
          },
          "metaLine": 18,
          "metaExportName": "meta"
        }
      ]
    },
    {
      "path": "/api/capa/lookup",
      "id": "capa-lookup",
      "filePath": "app/api/capa/lookup/route.ts",
      "methods": [
        {
          "method": "POST",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/capa/summary-by-bjd",
      "id": "capa-summary-by-bjd",
      "filePath": "app/api/capa/summary-by-bjd/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/health",
      "id": "health",
      "filePath": "app/api/health/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/map-summary",
      "id": "map-summary",
      "filePath": "app/api/map-summary/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/parcel/by-latlng",
      "id": "parcel-by-latlng",
      "filePath": "app/api/parcel/by-latlng/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/parcel/by-pnu",
      "id": "parcel-by-pnu",
      "filePath": "app/api/parcel/by-pnu/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/polygon/by-bjd",
      "id": "polygon-by-bjd",
      "filePath": "app/api/polygon/by-bjd/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/reconcile",
      "id": "reconcile",
      "filePath": "app/api/reconcile/route.ts",
      "methods": [
        {
          "method": "POST",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/refresh-mv",
      "id": "refresh-mv",
      "filePath": "app/api/refresh-mv/route.ts",
      "methods": [
        {
          "method": "POST",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/search",
      "id": "search",
      "filePath": "app/api/search/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    },
    {
      "path": "/api/transactions/by-bjd",
      "id": "transactions-by-bjd",
      "filePath": "app/api/transactions/by-bjd/route.ts",
      "methods": [
        {
          "method": "GET",
          "meta": null,
          "metaLine": 0,
          "metaExportName": null
        }
      ]
    }
  ],
  "services": [
    {
      "id": "kakao",
      "name": "Kakao Developers",
      "category": "geocoding",
      "consoleUrl": "https://developers.kakao.com/console/app/1424714",
      "envKeys": [
        "NEXT_PUBLIC_KAKAO_JS_KEY",
        "KAKAO_REST_KEY"
      ],
      "expiry": null,
      "dailyLimit": "300,000건/일 (지오코딩 / 역지오코딩 각각)",
      "issueGuide": "1. https://developers.kakao.com 접속 → Google 로그인\n2. 앱 ID 1424714 (이름: kepco_web) 선택 또는 새 앱 생성\n3. 좌측 [플랫폼] → Web 플랫폼 등록 → 도메인 추가\n   - http://localhost:3000 (개발)\n   - https://sunlap.kr (운영)\n4. 좌측 [앱 키] → JavaScript 키, REST API 키 복사\n5. .env.local 에 등록\n   - NEXT_PUBLIC_KAKAO_JS_KEY=...\n   - KAKAO_REST_KEY=...",
      "usageExample": "# 주소 → 좌표 (지오코딩)\nGET https://dapi.kakao.com/v2/local/search/address?query=서울 강남대로 1\nHeaders:\n  Authorization: KakaoAK ${KAKAO_REST_KEY}",
      "notes": "- JavaScript 키는 브라우저 노출 OK — 콘솔 도메인 화이트리스트로 보호됨\n- REST 키는 절대 클라이언트 노출 X → 반드시 API Route 경유\n- 일 한도 초과 시 자동 차단 (과금 X), 자정 지나면 복구\n- 한국 주소 정확도 가장 높음 — 1순위 지오코더",
      "filePath": "app/admin/api-manager/_lib/services/kakao.ts",
      "metaLine": 3,
      "consumedBy": []
    }
  ],
  "warnings": [
    "/api/admin/crawl DELETE: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaDELETE` 추가 필요",
    "/api/admin/crawl GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/admin/crawl PATCH: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaPATCH` 추가 필요",
    "/api/admin/crawl POST: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaPOST` 추가 필요",
    "/api/admin/crawl/regions GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/admin/users DELETE: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaDELETE` 추가 필요",
    "/api/admin/users GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/admin/users PATCH: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaPATCH` 추가 필요",
    "/api/admin/users POST: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaPOST` 추가 필요",
    "/api/admin/users PUT: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaPUT` 추가 필요",
    "/api/buildings/by-pnu GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/capa/by-bjd GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/capa/lookup POST: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaPOST` 추가 필요",
    "/api/capa/summary-by-bjd GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/health GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/map-summary GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/parcel/by-latlng GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/parcel/by-pnu GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/polygon/by-bjd GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/reconcile POST: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaPOST` 추가 필요",
    "/api/refresh-mv POST: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaPOST` 추가 필요",
    "/api/search GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요",
    "/api/transactions/by-bjd GET: meta 미정의 — route.ts 에 `export const meta` 또는 `export const metaGET` 추가 필요"
  ]
} as GeneratedManifest;
